$foregroundCol = 0xffc8dae6
$backgroundCol = 0xff101316
$color0 = 0xff101316
$color1 = 0xffA5ACB1
$color2 = 0xffC9B8B7
$color3 = 0xff94B4CD
$color4 = 0xffADBACA
$color5 = 0xff89BEE2
$color6 = 0xffCBBEC1
$color7 = 0xffc8dae6
$color8 = 0xff8c98a1
$color9 = 0xffA5ACB1
$color10 = 0xffC9B8B7
$color11 = 0xff94B4CD
$color12 = 0xffADBACA
$color13 = 0xff89BEE2
$color14 = 0xffCBBEC1
$color15 = 0xffc8dae6
